src/Entity/Signaux.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SignauxRepository")
 */
class Signaux
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_placement;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $evenement;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $gain;

    /**
     * @ORM\Column(type="integer")
     */
    private $status;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $placement;

    public function __construct()
    {
        $this->date_placement = new \DateTime();
        $this->gain = 0;
        $this->status = 0;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDatePlacement(): ?\DateTimeInterface
    {
        return $this->date_placement;
    }

    public function setDatePlacement(\DateTimeInterface $date_placement): self
    {
        $this->date_placement = $date_placement;

        return $this;
    }

    public function getEvenement(): ?string
    {
        return $this->evenement;
    }

    public function setEvenement(string $evenement): self
    {
        $this->evenement = $evenement;

        return $this;
    }

    public function getGain(): ?float
    {
        return $this->gain;
    }

    public function setGain(float $gain): self
    {
        $this->gain = $gain;

        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->status;
    }

    public function setStatus(int $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getPlacement(): ?float
    {
        return $this->placement;
    }

    public function setPlacement(?float $placement): self
    {
        $this->placement = $placement;

        return $this;
    }
}

src/Form/SignauxType.php
<?php

namespace App\Form;

use App\Entity\Signaux;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class SignauxType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            //->add('date_placement')
            ->add('evenement')
            ->add('placement')
            ->add('gain')
            ->add('status', ChoiceType::class, [
                'choices' => [
                    'En cours' => 0,
                    'Terminé' => 1,
                ],
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Signaux::class,
        ]);
    }
}

src/Controller/SignauxController.php
<?php

namespace App\Controller;

use App\Entity\Signaux;
use App\Form\SignauxType;
use App\Repository\SignauxRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/dashboard/signaux")
 */
class SignauxController extends AbstractController
{
    /**
     * @Route("/", name="signaux_index", methods={"GET"})
     */
    public function index(SignauxRepository $signauxRepository): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $user = $this->getUser();
        if($user->getRole() == 1)
            return $this->redirectToRoute('inscription_home');

        return $this->render('signaux/index.html.twig', [
            'signauxes' => $signauxRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="signaux_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $signaux = new Signaux();
        $form = $this->createForm(SignauxType::class, $signaux);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($signaux);
            $entityManager->flush();

            return $this->redirectToRoute('signaux_index');
        }

        return $this->render('signaux/new.html.twig', [
            'signaux' => $signaux,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="signaux_show", methods={"GET"})
     */
    public function show(Signaux $signaux): Response
    {
        return $this->render('signaux/show.html.twig', [
            'signaux' => $signaux,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="signaux_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Signaux $signaux): Response
    {
        $form = $this->createForm(SignauxType::class, $signaux);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('signaux_index');
        }

        return $this->render('signaux/edit.html.twig', [
            'signaux' => $signaux,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="signaux_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Signaux $signaux): Response
    {
        if ($this->isCsrfTokenValid('delete'.$signaux->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($signaux);
            $entityManager->flush();
        }

        return $this->redirectToRoute('signaux_index');
    }
}

templates/signaux/_delete_form.html.twig
<form method="post" action="{{ path('signaux_delete', {'id': signaux.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ signaux.id) }}">
    <button class="btn btn-primary">Delete</button>
</form>

templates/signaux/_form.html.twig
<style type="text/css">
    button[type=submit]{float: right;}
</style>
<div class="col-sm-6 col-sm-offset-3" style="margin:auto">
	{{ form_start(form) }}	
		<div class="label label-error">{{ form_errors(form) }}</div>
		    <div class="form-group mb-4">
		        <label>Evenement</label>
		        {{ form_widget(form.evenement, {'attr': {'class': 'form-control'}}) }}
		    </div>
		    <div class="form-group mb-4">
		        <label>Placement (€)</label>
		        {{ form_widget(form.placement, {'attr': {'class': 'form-control'}}) }}
		    </div>
		    <div class="form-group mb-4">
		        <label>Gain (€)</label>
		        {{ form_widget(form.gain, {'attr': {'class': 'form-control'}}) }}
		    </div>
		    <div class="form-group mb-4">
		        <label>Status</label>
		        {{ form_widget(form.status, {'attr': {'class': 'form-control'}}) }}
		    </div>
		{{ form_widget(form._token) }}
	    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
	{{ form_end(form) }}
</div>

templates/signaux/edit.html.twig
{% extends 'backoffice/layout.html.twig' %}
{% block title %} {{parent()}} | Liste des abonnés {% endblock %}
{% block meta %}
    <meta name="description" content="">
{% endblock %}

{% block stylesheets %}
    {{parent()}}

{% endblock %}

{% block title_page %}
    <h4>Editer signaux</h4>
{% endblock %}

{% block body_dash %}
	
    {{ include('signaux/_form.html.twig', {'button_label': 'Update'}) }}
{% endblock %}

templates/signaux/index.html.twig
{% extends 'backoffice/layout.html.twig' %}
{% block title %} {{parent()}} | Liste des abonnés {% endblock %}
{% block meta %}
    <meta name="description" content="">
{% endblock %}

{% block stylesheets %}
    {{parent()}}

{% endblock %}

{% block title_page %}
    <div style="display:flex; align-items:center">
        <h4>Liste des signaux</h4> 
        <a href="{{ path('signaux_new') }}" class="btn btn-button-4">Nouveau signal</a>
    </div>
{% endblock %}

{% block body_dash %}
    <div class="table-responsive mb-4">
        <table id="zero-config" class="table table-bordered" style="width:100%">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Date_placement</th>
                    <th>Evenement</th>
                    <th>Placement (€)</th>
                    <th>Gain (€)</th>
                    <th>Status</th>
                    <th>actions</th>
                </tr>
            </thead>
            <tbody>
            {% for signaux in signauxes %}
                <tr>
                    <td>{{ signaux.id }}</td>
                    <td>{{ signaux.datePlacement ? signaux.datePlacement|date('Y-m-d H:i') : '' }}</td>
                    <td>{{ signaux.evenement }}</td>
                    <td>{{ signaux.placement }}</td>
                    <td>{{ signaux.gain }}</td>
                    <td>{{ signaux.status == 0 ? 'En cours' : 'Terminé'}}</td>
                    <td style="text-align:center">
                        <a href="{{ path('signaux_edit', {'id': signaux.id}) }}" class="btn btn-primary" style="margin-bottom: 3px;">edit</a>
                        {{ include('signaux/_delete_form.html.twig') }}
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="6">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    
{% endblock %}
{% block javascripts %}
    {{parent()}}
    <script type="text/javascript">
        $('#modernSidebar .menu > a.signaux').addClass('open');
    </script>
{% endblock %}

templates/signaux/new.html.twig
{% extends 'backoffice/layout.html.twig' %}
{% block title %} {{parent()}} | Liste des abonnés {% endblock %}
{% block meta %}
    <meta name="description" content="">
{% endblock %}

{% block stylesheets %}
    {{parent()}}

{% endblock %}

{% block title_page %}
    <h4>Nouveau signaux</h4>
{% endblock %}

{% block body_dash %}

    {{ include('signaux/_form.html.twig') }}

{% endblock %}

templates/signaux/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Signaux{% endblock %}

{% block body %}
    <h1>Signaux</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ signaux.id }}</td>
            </tr>
            <tr>
                <th>Date_placement</th>
                <td>{{ signaux.datePlacement ? signaux.datePlacement|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Evenement</th>
                <td>{{ signaux.evenement }}</td>
            </tr>
            <tr>
                <th>Gain</th>
                <td>{{ signaux.gain }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ signaux.status }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('signaux_index') }}">back to list</a>

    <a href="{{ path('signaux_edit', {'id': signaux.id}) }}">edit</a>

    {{ include('signaux/_delete_form.html.twig') }}
{% endblock %}